// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8kj9pGny2Z40peIyXp5hA1BSF67rAjvU',
    appId: '1:573201705570:web:1c6d99139a044f50d2ff3b',
    messagingSenderId: '573201705570',
    projectId: 'portfolio-2e9ad',
    authDomain: 'portfolio-2e9ad.firebaseapp.com',
    storageBucket: 'portfolio-2e9ad.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJwWv_3Xvzdf__TyoO_6izY2WmartK7eE',
    appId: '1:573201705570:android:6a973eb0fa14efb6d2ff3b',
    messagingSenderId: '573201705570',
    projectId: 'portfolio-2e9ad',
    storageBucket: 'portfolio-2e9ad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5u0Dqh-c4-J7XWB4O6IqKeZ6zQITu5sk',
    appId: '1:573201705570:ios:d9ef2d457b309395d2ff3b',
    messagingSenderId: '573201705570',
    projectId: 'portfolio-2e9ad',
    storageBucket: 'portfolio-2e9ad.firebasestorage.app',
    iosBundleId: 'com.heet.portfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5u0Dqh-c4-J7XWB4O6IqKeZ6zQITu5sk',
    appId: '1:573201705570:ios:3269075669d96221d2ff3b',
    messagingSenderId: '573201705570',
    projectId: 'portfolio-2e9ad',
    storageBucket: 'portfolio-2e9ad.firebasestorage.app',
    iosBundleId: 'com.example.portfolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8kj9pGny2Z40peIyXp5hA1BSF67rAjvU',
    appId: '1:573201705570:web:4ae971dbef85f6b9d2ff3b',
    messagingSenderId: '573201705570',
    projectId: 'portfolio-2e9ad',
    authDomain: 'portfolio-2e9ad.firebaseapp.com',
    storageBucket: 'portfolio-2e9ad.firebasestorage.app',
  );
}
